# Assignment: Various Mathematical and Statistical Concepts

## Task 1: Apply Bayes' Theorem to solve a medical diagnosis problem

In [1]:
# Bayes' Theorem example for a medical diagnosis problem
def bayes_theorem(prior_A, prob_B_given_A, prob_B):
    return (prob_B_given_A * prior_A) / prob_B

# Example values
prior_disease = 0.01  # Prior probability of having the disease
prob_positive_given_disease = 0.95  # Probability of a positive test given the disease
prob_positive = 0.05  # Probability of a positive test

# Applying Bayes' Theorem
posterior = bayes_theorem(prior_disease, prob_positive_given_disease, prob_positive)
print(f"Probability of having the disease given a positive test: {posterior:.4f}")

Probability of having the disease given a positive test: 0.1900


## Task 2: Find the eigenvalues and corresponding eigenvectors of a given matrix

In [2]:
import numpy as np

# Define a matrix
matrix = np.array([[4, -2, 1],
                  [-2, 4, -2],
                  [1, -2, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[7.11902668 2.56837289 1.31260044]

Eigenvectors:
[[ 0.57864919 -0.76930576  0.27080208]
 [-0.66960599 -0.25857088  0.69625349]
 [ 0.46561028  0.58421721  0.66475357]]


## Task 3: Calculate the determinant of a 3x3 matrix and find its inverse if possible

In [3]:
# Define a 3x3 matrix
matrix = np.array([[1, 2, 3],
                  [0, 1, 4],
                  [5, 6, 0]])

# Calculate determinant
determinant = np.linalg.det(matrix)
print(f"Determinant: {determinant:.2f}")

# Calculate inverse if determinant is non-zero
if determinant != 0:
    inverse = np.linalg.inv(matrix)
    print("\nInverse:")
    print(inverse)
else:
    print("\nMatrix is singular and does not have an inverse.")

Determinant: 1.00

Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


## Task 4: Describe the properties and applications of the Normal distribution and calculate probabilities using its properties

### Properties of Normal Distribution
- The normal distribution is symmetric about the mean.
- The mean, median, and mode of the distribution are equal.
- The distribution is defined by its mean (μ) and standard deviation (σ).
- Approximately 68% of the data falls within one standard deviation of the mean, 95% within two, and 99.7% within three (Empirical Rule).

### Applications of Normal Distribution
- In finance, for modeling asset returns.
- In quality control, for representing variation in manufacturing processes.
- In psychology, for intelligence testing scores.
- In natural and social sciences, for various phenomena such as heights, measurement errors, etc.

In [4]:
import scipy.stats as stats

# Define mean and standard deviation
mean = 0
std_dev = 1

# Create a normal distribution
distribution = stats.norm(mean, std_dev)

# Calculate probability P(X <= 1.96)
probability = distribution.cdf(1.96)
print(f"P(X <= 1.96): {probability:.4f}")

# Calculate probability P(X > 1.96)
probability = 1 - distribution.cdf(1.96)
print(f"P(X > 1.96): {probability:.4f}")

# Calculate probability P(-1 <= X <= 1)
probability = distribution.cdf(1) - distribution.cdf(-1)
print(f"P(-1 <= X <= 1): {probability:.4f}")

P(X <= 1.96): 0.9750
P(X > 1.96): 0.0250
P(-1 <= X <= 1): 0.6827
